# NOAA Tides
#   Harve Cedars
- platform: noaa_tides
  station_id: 8533862
  name: North Beach
- platform: noaa_tides
  station_id: 8533780
  name: Flat Creek 
- platform: noaa_tides
  station_id: 8533738
  name: Loveladies Harbor
#   Habersham
- platform: noaa_tides
  station_id: TEC3327
  name: Euhaw Creek
- platform: noaa_tides
  station_id: 8667909
  name: Albergottie Creek
- platform: noaa_tides
  station_id: 8668223
  name: Hwy 170


# TODOIST
- platform: rest
  name: Home Assistant
  method: GET
  resource: 'https://api.todoist.com/sync/v9/projects/get_data'
  params:
    project_id: 2200498431
  headers:
    Authorization: !secret todoist_api_token
  value_template: '{{ value_json[''project''][''id''] }}'
  json_attributes:
    - project
    - items
  scan_interval: 30  
  
- platform: rest
  name: Personal
  method: GET
  resource: 'https://api.todoist.com/sync/v9/projects/get_data'
  params:
    project_id: 2170688314
  headers:
    Authorization: !secret todoist_api_token
  value_template: '{{ value_json[''project''][''id''] }}'
  json_attributes:
    - project
    - items
  scan_interval: 30  
  
# Time/Date Sensors
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

    
#EPSON Workforce
- platform: epsonworkforce
  host: 192.168.1.159
  monitored_conditions:
  - black
  - yellow
  - magenta
  - cyan
  - clean
  
